# Generated by Django 4.2.11 on 2026-03-21 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='transaction',
        ),
        migrations.AddField(
            model_name='wallet',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('TRANSFER', 'Transfer')], default='DEPOSIT', max_length=10),
        ),
    ]
