# Generated by Django 6.0.3 on 2026-03-21 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_remove_wallet_transaction_wallet_transaction_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='amount',
            new_name='balance',
        ),
    ]
