# Generated by Django 6.0.3 on 2026-04-02 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0006_alter_asset_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='symbol',
            field=models.CharField(choices=[('BITCOIN', 'BTC'), ('ETHEREUM', 'ETH'), ('SOLANA', 'SOL'), ('BINANCECOIN', 'BNB'), ('RIPPLE', 'XRP'), ('CARDANO', 'ADA')], default='bitcoin', max_length=50),
        ),
    ]
